// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPITask.DAL.Context;

namespace WebAPITask.DAL.Migrations
{
    [DbContext(typeof(CrystalMindDbContext))]
    partial class CrystalMindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPITask.DAL.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f138a31e-3c81-481e-92de-d873d020b4d4"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1964),
                            Email = "ahmadsabry28@gmail.com",
                            FirstName = "Ahmed",
                            Gender = "M",
                            LastName = "Sabry"
                        },
                        new
                        {
                            Id = new Guid("f138a31e-3c81-481e-92de-d873d020b4d5"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1971),
                            Email = "mohamedsalah@gmail.com",
                            FirstName = "Mohamed",
                            Gender = "M",
                            LastName = "Salah"
                        });
                });

            modelBuilder.Entity("WebAPITask.DAL.Models.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AddressRank")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CustomerAddresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f138a31e-3c81-481e-92de-d873d020b000"),
                            Address = "Cairo - Egypt",
                            AddressRank = 2,
                            CustomerId = new Guid("f138a31e-3c81-481e-92de-d873d020b4d4")
                        },
                        new
                        {
                            Id = new Guid("f138a31e-3c81-481e-92de-d873d020b111"),
                            Address = "Alex - Egypt",
                            AddressRank = 1,
                            CustomerId = new Guid("f138a31e-3c81-481e-92de-d873d020b4d4")
                        },
                        new
                        {
                            Id = new Guid("f138a31e-3c81-481e-92de-d873d020b222"),
                            Address = "Liverpool - England",
                            AddressRank = 1,
                            CustomerId = new Guid("f138a31e-3c81-481e-92de-d873d020b4d5")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
